services:
  convert:
    entrypoint:
      - /lilypond/bin/convert-ly
      - --edit
    image: ghcr.io/williamjacksn/lilypond
    init: true
    volumes:
      - ./:/home/python/lilypond-files
    working_dir: /home/python/lilypond-files

  lilypond:
    image: ghcr.io/williamjacksn/lilypond
    init: true
    volumes:
      - ./:/home/python/lilypond-files
    working_dir: /home/python/lilypond-files

  publish:
    entrypoint:
      - /home/python/venv/bin/python
      - /home/python/lilypond-files/publish.py
    image: ghcr.io/williamjacksn/lilypond
    init: true
    volumes:
      - ./:/home/python/lilypond-files
    working_dir: /home/python/lilypond-files

  shell:
    entrypoint:
      - /bin/bash
    image: ghcr.io/williamjacksn/lilypond
    init: true
    volumes:
      - ./:/home/python/lilypond-files
    working_dir: /home/python/lilypond-files
